### ISSUE TITLE
Project Skeleton: Create Database with two tables - Users and Expenses

### ISSUE THREAD

**Issue by kristiyanpetkov** [kristiyanpetkov/scrum#1]
Users table:
![screenshot from 2016-06-29 17-22-48](https://cloud.githubusercontent.com/assets/12229738/16455768/37ff69c0-3e1e-11e6-8beb-3eb212af993a.png)

Expenses table:
![screenshot from 2016-06-29 17-22-58](https://cloud.githubusercontent.com/assets/12229738/16455772/3e17e8e6-3e1e-11e6-9e3e-919c55b34c77.png)

**Comment by mlesikov** [comment]
http://martinfowler.com/bliki/GivenWhenThen.html

**Comment by mlesikov** [comment]
https://github.com/cucumber/cucumber/wiki/Given-When-Then

https://www.mountaingoatsoftware.com/agile/user-stories

https://www.google.bg/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=writing+user+stories

https://plus.google.com/+MiroslavGenov/posts/fjjpasHrAoa

**Comment by mlesikov** [comment]
https://help.rallydev.com/writing-great-user-story

**Comment by mlesikov** [comment]
http://storiesonboard.com/
